- hosts: 127.0.0.1
  connection: local
  roles:
    - role: geerlingguy.java
      become: yes
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jre
    - role: geerlingguy.java
      become: yes
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
  vars:
    ebms_version: 2.18.0
    workdir: ~/ebms-adapter-demo/digipoort/
  tasks:
    - name: Create work directory if it does not exist
      file:
        path: "{{ workdir }}"
        state: directory
        mode: 0755
    - name: Download application
      get_url:
        url: https://github.com/eluinstra/ebms-admin/releases/download/ebms-admin-{{ ebms_version }}/ebms-admin-{{ ebms_version }}.jar
        dest: "{{ workdir }}ebms-admin-{{ ebms_version }}.jar"
        backup: true
    - name: Create properties file
      shell: |
        printf 'https.verifyHostnames=false
        ebms.jdbc.update=true' > {{ workdir }}ebms-admin.embedded.properties
      args:
        creates: "{{ workdir }}ebms-admin.embedded.properties"
    - name: Start application
      shell: java -cp ebms-admin-{{ ebms_version }}.jar nl.clockwork.ebms.admin.StartEmbedded -hsqldb -soap
      args:
        chdir: "{{ workdir }}" 
